import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Post app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-br from-blue-600 to-violet-600 text-white w-full h-full font-amsterdam"
    >
      <body>{children}</body>
    </html>
  );
}
